//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppVente.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produits
    {
        public int idProduit { get; set; }
        public string Designation { get; set; }
        public string Description { get; set; }
        public string CodeProduit { get; set; }
        public string PrixProduit { get; set; }
        public string QteMin { get; set; }
        public string QteCritique { get; set; }
    }
}
