//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Objects.DataClasses;

[assembly: System.Data.Entity.Core.Objects.DataClasses.EdmSchemaAttribute()]
namespace AppVente.Model1
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class bdVenteEntities1 : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet bdVenteEntities1 à l'aide de la chaîne de connexion trouvée dans la section 'bdVenteEntities1' du fichier de configuration d'application.
        /// </summary>
        public bdVenteEntities1() : base("name=bdVenteEntities1", "bdVenteEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet bdVenteEntities1.
        /// </summary>
        public bdVenteEntities1(string connectionString) : base(connectionString, "bdVenteEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet bdVenteEntities1.
        /// </summary>
        public bdVenteEntities1(EntityConnection connection) : base(connection, "bdVenteEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Produit> Produit
        {
            get
            {
                if ((_Produit == null))
                {
                    _Produit = base.CreateObjectSet<Produit>("Produit");
                }
                return _Produit;
            }
        }
        private ObjectSet<Produit> _Produit;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Produit. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToProduit(Produit produit)
        {
            base.AddObject("Produit", produit);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="bdVenteModel1", Name="Produit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produit : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Produit.
        /// </summary>
        /// <param name="idProduit">Valeur initiale de la propriété idProduit.</param>
        public static Produit CreateProduit(global::System.Int32 idProduit)
        {
            Produit produit = new Produit();
            produit.idProduit = idProduit;
            return produit;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idProduit
        {
            get
            {
                return _idProduit;
            }
            set
            {
                if (_idProduit != value)
                {
                    OnidProduitChanging(value);
                    ReportPropertyChanging("idProduit");
                    _idProduit = StructuralObject.SetValidValue(value, "idProduit");
                    ReportPropertyChanged("idProduit");
                    OnidProduitChanged();
                }
            }
        }
        private global::System.Int32 _idProduit;
        partial void OnidProduitChanging(global::System.Int32 value);
        partial void OnidProduitChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Designation
        {
            get
            {
                return _Designation;
            }
            set
            {
                OnDesignationChanging(value);
                ReportPropertyChanging("Designation");
                _Designation = StructuralObject.SetValidValue(value, true, "Designation");
                ReportPropertyChanged("Designation");
                OnDesignationChanged();
            }
        }
        private global::System.String _Designation;
        partial void OnDesignationChanging(global::System.String value);
        partial void OnDesignationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CodeProduit
        {
            get
            {
                return _CodeProduit;
            }
            set
            {
                OnCodeProduitChanging(value);
                ReportPropertyChanging("CodeProduit");
                _CodeProduit = StructuralObject.SetValidValue(value, "CodeProduit");
                ReportPropertyChanged("CodeProduit");
                OnCodeProduitChanged();
            }
        }
        private Nullable<global::System.Int32> _CodeProduit;
        partial void OnCodeProduitChanging(Nullable<global::System.Int32> value);
        partial void OnCodeProduitChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PrixProduit
        {
            get
            {
                return _PrixProduit;
            }
            set
            {
                OnPrixProduitChanging(value);
                ReportPropertyChanging("PrixProduit");
                _PrixProduit = StructuralObject.SetValidValue(value, "PrixProduit");
                ReportPropertyChanged("PrixProduit");
                OnPrixProduitChanged();
            }
        }
        private Nullable<global::System.Int32> _PrixProduit;
        partial void OnPrixProduitChanging(Nullable<global::System.Int32> value);
        partial void OnPrixProduitChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QteMin
        {
            get
            {
                return _QteMin;
            }
            set
            {
                OnQteMinChanging(value);
                ReportPropertyChanging("QteMin");
                _QteMin = StructuralObject.SetValidValue(value, "QteMin");
                ReportPropertyChanged("QteMin");
                OnQteMinChanged();
            }
        }
        private Nullable<global::System.Int32> _QteMin;
        partial void OnQteMinChanging(Nullable<global::System.Int32> value);
        partial void OnQteMinChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QteCritique
        {
            get
            {
                return _QteCritique;
            }
            set
            {
                OnQteCritiqueChanging(value);
                ReportPropertyChanging("QteCritique");
                _QteCritique = StructuralObject.SetValidValue(value, "QteCritique");
                ReportPropertyChanged("QteCritique");
                OnQteCritiqueChanged();
            }
        }
        private Nullable<global::System.Int32> _QteCritique;
        partial void OnQteCritiqueChanging(Nullable<global::System.Int32> value);
        partial void OnQteCritiqueChanged();

        #endregion

    }

    #endregion

}
